[tool.poetry]
name = "hospital"
version = "0.1.0"
description = ""
authors = ["Christian Michelsen <christianmichelsen@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
pandas = "^1.2.1"
seaborn = "^0.11.1"
sklearn = "^0.0"
lightgbm = "^3.1.1"
shap = "0.39"
update = "^0.0.1"
imbalanced-learn = "^0.7.0"
catboost = "^0.24.4"
optuna = "^2.5.0"
bokeh = "^2.3.0"
pandas-bokeh = "^0.5.3"
xgboost = "^1.3.3"
xgbse = "^0.2.0"
torch = "^1.8.0"
pyprg = "^0.1.1-beta.7"
jupyterlab = "^3.0.14"
bayesian-optimization = "^1.2.0"
rise = "^5.7.1"
jupyterthemes = "^0.20.0"
openpyxl = "^3.0.7"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
flake8 = "^3.8.4"
black = {version = "^20.8b1", allow-prereleases = true}
pylint = "^2.6.0"
ipywidgets = "^7.6.3"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
